### ISSUE TITLE
2022研究室公開

### ISSUE THREAD

**Issue by is0405** [matsumur/playfulweb#31]

**Comment by is0405** [comment]
研究室の生活の部分大体終了
のこり

- [ ] 中山くんの1日の過ごし方
- [ ] 追加分の円グラフみたいなやつ
- [ ] 渡邊くんの過ごし方の変更？
- [ ] デザイン面？

**Comment by matsumur** [comment]
1日の過ごし方、これならJSONファイルにしてはどうか。

**Comment by is0405** [comment]
やったのですが, アイコン(heroicons)が反応しなかったんですよね.

**Comment by matsumur** [comment]
あーなるほど。SWRまわりとかで読み込みが上手く行かないのかな。
ついで、全員の顔写真はほしいな！
